In [51]:
import pandas as pd

In [52]:
df= pd.read_csv("C:/Users/Sahil/Downloads/customer_shopping_behavior.csv")

In [53]:
# Imp. NOTE
# If you see = with df[...], the DataFrame WILL change.

In [54]:
df.tail()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [56]:
df.describe()                      #describe only numericals

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [57]:
df.describe(include ='all')                    #gives numerical and catagorical column

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [58]:
df.isnull().sum()          #total null values in each column

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [59]:
df["Customer ID"].duplicated().sum()

np.int64(0)

In [60]:
df.drop_duplicates("Customer ID")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [61]:
(df.columns)

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [62]:
df.rename(columns= {'Customer ID': 'customer_id'}, inplace= True)        # why used "inplace=true"?, this renames in existing dataset & doesn't create any new dataframe/dataset.

In [63]:
(df.columns)

Index(['customer_id', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [64]:
df.head(5)

,customer_id,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [65]:
df2= df.rename(columns ={'Customer ID':'customer_id'})      #here we made another dataframe/dataset ie, df2 which will have renamed columned and our raw data is preserved.

In [66]:
(df2)

,customer_id,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [67]:
df.isnull().sum()

customer_id                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [68]:
df['Review Rating']= df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [69]:
df.isnull().sum()

customer_id               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [70]:
df.columns= df.columns.str.lower()

In [71]:
df.columns=df.columns.str.replace(' ','_')

In [72]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [73]:
df=df.rename(columns= {'purchase_amount_(usd)' : 'purchase_amount',
                     'promo_code_used': 'promocode_used'})

In [74]:
df

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promocode_used,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [75]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promocode_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [76]:
df.location

0            Kentucky
1               Maine
2       Massachusetts
3        Rhode Island
4              Oregon
            ...
3895         Virginia
3896             Iowa
3897       New Jersey
3898        Minnesota
3899       California
Name: location, Length: 3900, dtype: object

In [77]:
len(df)                                         #tells no. of rows

3900

In [78]:
df.shape[0]                                     #tells no. of rows

3900

In [79]:
df.shape[1]                                      #tells no. of columns

18

In [80]:
df.size                                        #tells total no.of elements(rows * columns), i.e 3900*18

70200

In [81]:
# To create a new column
#df['column_name'] =  value(can be integar or string)                  #whatever u write in value place, it will appear in each rows of the new column

In [82]:
#ADD/Create a new column(age_group), need to classify age into diffenet age_groups, like- Young adults,adults, seniors etc

labels=['Young Adults','Adults','Middle-Age','Seniors']
df['age_group']= pd.qcut(df['age'], q=4, labels= labels)


# NOTE- Query Explanation-   df['age_group'] - This creates the new column(age_group) in the dataframe.
#                            pd.qcut  - qcut is a funtion that splits the column or used to split data into equal-sized groups or It divides your data into bins so that each bin has (almost) the same number of values.
#                                         while pd. is used because pandas was imported as pd and this funtion(qcut) was inside pandas.                                                   

#                            then we need to tell which column to cut, hence ['age'] is wrriten & it is inside df so it is specified.

# On more interest thing to note that, we used = here that means assignment is given hence, whatever is right side will get included in the actual/original dataset

In [83]:
df[['age', 'age_group']].head(10)                                 #need to write double [[ to call columns , if use one then Pandas will try to create new 
                                                                                                 # column

   age     age_group
0   55    Middle-Age
1   19  Young Adults
2   50    Middle-Age
3   21  Young Adults
4   45    Middle-Age
5   46    Middle-Age
6   63       Seniors
7   27  Young Adults
8   26  Young Adults
9   57    Middle-Age

In [84]:
#Q - how often a customer purchases?
df['frequency_of_purchases'].unique()                                                  #Gives unique values in a column

array(['Fortnightly', 'Weekly', 'Annually', 'Quarterly', 'Bi-Weekly',
       'Monthly', 'Every 3 Months'], dtype=object)

In [85]:
#Creating a new column- 'purchase_frequency_days'                                               
mapping= {                                                                                       #this is called creating dictionary
    'Fortnightly':14,                                                                #numbers r easy to analyse than texts thats why we did this.
    'Weekly':7,
    'Annually':365,                                       
    'Quarterly':120,
    'Bi-Weekly': 14,
    'Monthly':30,
    'Every 3 Months': 90,
}
    
df['purchase_frequency_days']= df['frequency_of_purchases'].map(mapping)

In [86]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                      120              Quarterly
7                        7                 Weekly
8                      365               Annually
9                      120              Quarterly

In [87]:
(df)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promocode_used,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,Middle-Age,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,Young Adults,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,Middle-Age,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,Young Adults,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,Middle-Age,365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly,Adults,7
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly,Middle-Age,14
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly,Middle-Age,120
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly,Adults,7
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly,Middle-Age,120

In [88]:
df[['discount_applied','promocode_used']].head(15)

   discount_applied promocode_used
0               Yes            Yes
1               Yes            Yes
2               Yes            Yes
3               Yes            Yes
4               Yes            Yes
5               Yes            Yes
6               Yes            Yes
7               Yes            Yes
8               Yes            Yes
9               Yes            Yes
10              Yes            Yes
11              Yes            Yes
12              Yes            Yes
13              Yes            Yes
14              Yes            Yes

In [89]:
#they both columns looking same..
# well lets see if they r same or not, if same, we will drop one.

(df['discount_applied'] == df['promocode_used']).all()

np.True_

In [90]:
df[['discount_applied','promocode_used']]

     discount_applied promocode_used
0                 Yes            Yes
1                 Yes            Yes
2                 Yes            Yes
3                 Yes            Yes
4                 Yes            Yes
...               ...            ...
3895               No             No
3896               No             No
3897               No             No
3898               No             No
3899               No             No

[3900 rows x 2 columns]

In [91]:
# df['discount_applied'] = df['promocode_used']                                      #this query make both column same

In [92]:
# Ah, perfect — now it’s clear what you want. ✅ You want to **check if two columns are equal row by row**. Here are the best ways to do it in pandas:

# ---

## 1️- Row-by-row comparison (creates a new column)

# ```python
# df['same'] = df['column1'] == df['column2']
# ```

# * This checks **each row individually**
# * Result is a Series of `True` / `False`

# **Example:**

# ```python
# df = pd.DataFrame({
#     'A': [1, 2, 3],
#     'B': [1, 5, 3]
# })

# df['same'] = df['A'] == df['B']
# print(df)
# ```

# **Output:**

# ```
#    A  B   same
# 0  1  1   True
# 1  2  5  False
# 2  3  3   True
# ```

# ---

# ## 2️- Check if **all rows are the same** (Gives single True/False, thats it nthng else)

# ```python
# (df['column1'] == df['column2']).all()
# ```

# * Returns **True** if every row matches
# * Returns **False** if any row is different

# **Example:**

# ```python
# (df['A'] == df['B']).all()
# # Output: False
# ```

# ---

# ## 3️⃣ Check if **entire columns are identical** including index and dtype

# ```python
# df['A'].equals(df['B'])
# ```

# * Returns **True** only if **all values AND index match exactly**
# * Useful when you want a strict check

# ---

# ### ✅ Recommended approach

# * **Want row-by-row info:** use `==` and maybe create a new column
# * **Want one True/False if all match:** wrap it in `.all()`
# * **Want strict equality including index:** use `.equals()`

# ---

# If you want, I can write a **super safe one-liner** that shows **both row-by-row differences and whether all rows match** in one go. It’s really handy for data checks.

# Do you want me to do that?

In [93]:
#so bth columns r same, hence we'll drop one
df= df.drop('promocode_used', axis=1)                                    #axis=1, 1 bcz columns r vertical, so for vertical
                                                                         #for vertical(columns)- axis=1
                                                                         #for horizontal(rows)- axis=0

In [94]:
len(df.columns)

19

In [95]:
#now data cleaning is done
#so NOW, LETS IMPORT this cleaned DATA to PostgreSQL(PgAdmin)
# Two methods-
# 1- export this cleaned data as CSV,then import it in PGADMIN
# 2- Write a code here which will send this data directly to postgreSQL(whatever database we name)

In [96]:
# we will use 2nd method,cz its Better

#          !pip install psycopg2-binary sqlalchemy                               #used "!" before pip... ,bcz Jupyter cells run Python code, not shell 
                                                                                 #commands,so ! tells its command and not code
                                                                                                                                 #If postgreSQL, then-
                                                                                                             # !Pip install psycopg2-binary sqlalchemy
                                                                                                                                 #If MySQL
                                                                                                             #        !pip install pymysql sqlalchemy 
                                                                                                                                 #If MS SQL Server 
                                                                                                             #         !pip install pyodbc sqlalchemy

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: Invalid requirement: '#used': Expected package name at the start of dependency specifier
    #used
    ^

In [98]:
from sqlalchemy import create_engine

engine= create_engine("postgresql+psycopg2://postgres:123456@localhost:5432/billa")

df.to_sql(
    name= "thomas",
    con= engine,
    if_exists= "replace",
    index= False
)




#THings ABT above code-
# -engine is basically a bridge/connection btw pandas & postgreSQL
# -con is connection in short
# -One-line mental rule (remember this)

# engine = where to send data
# to_sql = send the data

# That’s it.

900

In [99]:
df.shape

(3900, 19)

In [102]:
pd.read_sql ("select * from thomas;", engine)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-Age,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adults,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-Age,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adults,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-Age,365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,32,Venmo,Weekly,Adults,7
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,41,Bank Transfer,Bi-Weekly,Middle-Age,14
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,24,Venmo,Quarterly,Middle-Age,120
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,24,Venmo,Weekly,Adults,7
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,33,Venmo,Quarterly,Middle-Age,120

In [ ]:
#now we'll answer business questions on PgAdmin
#See u there :)